// <auto-generated />
using System;
using CardGameStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardGameStore.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_admin_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("link_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("announcements");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("ActorUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("ActorUserName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_user_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_hash");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.Championship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_admin_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<int>("EntryFeeInCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entry_fee_in_cents");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("game");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_participants");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RegistrationDeadline")
                        .HasColumnType("TEXT")
                        .HasColumnName("registration_deadline");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_championships_start_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_championships_status");

                    b.ToTable("championships");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.ChampionshipParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ChampionshipId")
                        .HasColumnType("TEXT")
                        .HasColumnName("championship_id");

                    b.Property<Guid?>("ComandaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("comanda_id");

                    b.Property<string>("DeckName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("deck_name");

                    b.Property<int?>("Placement")
                        .HasColumnType("INTEGER")
                        .HasColumnName("placement");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("player_number");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("registered_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.HasIndex("UserId");

                    b.HasIndex("ChampionshipId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_championship_participants_unique");

                    b.ToTable("championship_participants");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.Comanda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChampionshipId")
                        .HasColumnType("TEXT")
                        .HasColumnName("championship_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("closed_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("opened_at");

                    b.Property<int>("PointsApplied")
                        .HasColumnType("INTEGER")
                        .HasColumnName("points_applied");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("TableIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("table_identifier");

                    b.Property<int>("TotalInCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_in_cents");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ChampionshipId")
                        .HasDatabaseName("ix_comandas_championship");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_comandas_status");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_comandas_user_status");

                    b.ToTable("comandas");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.ComandaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_by_user_id");

                    b.Property<string>("CardCacheId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("card_cache_id");

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("comanda_id");

                    b.Property<string>("ItemNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_name_snapshot");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<int>("SubtotalInCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subtotal_in_cents");

                    b.Property<int>("UnitPriceInCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_price_in_cents");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId")
                        .HasDatabaseName("ix_comanda_items_comanda");

                    b.HasIndex("ProductId");

                    b.ToTable("comanda_items");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.CookieConsent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Accepted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accepted");

                    b.Property<DateTime>("ConsentAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("consent_at");

                    b.Property<string>("IpHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_hash");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("policy_version");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ConsentAt")
                        .HasDatabaseName("ix_cookie_consents_consent_at");

                    b.HasIndex("UserId");

                    b.ToTable("cookie_consents");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.Crediario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("AbertoPorAdminId")
                        .HasColumnType("TEXT")
                        .HasColumnName("aberto_por_admin_id");

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("comanda_id");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_abertura");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_pagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<Guid?>("PagoPorAdminId")
                        .HasColumnType("TEXT")
                        .HasColumnName("pago_por_admin_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.Property<int>("ValorEmCentavos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("valor_em_centavos");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_crediarios_status");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_crediarios_user_status");

                    b.ToTable("crediarios");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.LgpdRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AdminResponse")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("admin_response");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_type");

                    b.Property<string>("RequesterCpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("requester_cpf");

                    b.Property<string>("RequesterEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("requester_email");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("requester_name");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RequesterEmail")
                        .HasDatabaseName("ix_lgpd_requests_email");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_lgpd_requests_status");

                    b.HasIndex("UserId");

                    b.ToTable("lgpd_requests");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_featured");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("minimum_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PriceInCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price_in_cents");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock_quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_products_category");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_products_is_active");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasFilter("barcode IS NOT NULL")
                        .HasDatabaseName("ix_products_barcode");

                    b.ToTable("products");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConsentAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("consent_at");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_reset_token_expiry");

                    b.Property<int>("PointsBalance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("points_balance");

                    b.Property<DateTime?>("PointsExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("points_expires_at");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("TEXT")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_users_cpf")
                        .HasFilter("cpf IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("WhatsApp")
                        .HasDatabaseName("ix_users_whatsapp");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@cardgamestore.com.br",
                            IsActive = true,
                            Name = "Maikon",
                            PasswordHash = "$2b$12$2FtwJhHP3JiQZjXb.f19B.ulmS5t2jdIQbKAPhPYP22AT.0ptsVPC",
                            PointsBalance = 0,
                            Role = "Admin",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.ChampionshipParticipant", b =>
                {
                    b.HasOne("CardGameStore.Models.PostgreSQL.Championship", "Championship")
                        .WithMany("Participants")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardGameStore.Models.PostgreSQL.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CardGameStore.Models.PostgreSQL.User", "User")
                        .WithMany("ChampionshipParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Championship");

                    b.Navigation("Comanda");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.Comanda", b =>
                {
                    b.HasOne("CardGameStore.Models.PostgreSQL.Championship", "Championship")
                        .WithMany("Comandas")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CardGameStore.Models.PostgreSQL.User", "User")
                        .WithMany("Comandas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Championship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.ComandaItem", b =>
                {
                    b.HasOne("CardGameStore.Models.PostgreSQL.Comanda", "Comanda")
                        .WithMany("Items")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardGameStore.Models.PostgreSQL.Product", "Product")
                        .WithMany("ComandaItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Comanda");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.CookieConsent", b =>
                {
                    b.HasOne("CardGameStore.Models.PostgreSQL.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.Crediario", b =>
                {
                    b.HasOne("CardGameStore.Models.PostgreSQL.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CardGameStore.Models.PostgreSQL.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.LgpdRequest", b =>
                {
                    b.HasOne("CardGameStore.Models.PostgreSQL.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.Championship", b =>
                {
                    b.Navigation("Comandas");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.Comanda", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.Product", b =>
                {
                    b.Navigation("ComandaItems");
                });

            modelBuilder.Entity("CardGameStore.Models.PostgreSQL.User", b =>
                {
                    b.Navigation("ChampionshipParticipants");

                    b.Navigation("Comandas");
                });
#pragma warning restore 612, 618
        }
    }
}
