CREATE TABLE usuario(
    ID_USUARIO BIGINT PRIMARY KEY,
    NOME VARCHAR(60)  NOT NULL,
    TELEFONE NUMBER NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PERFIL VARCHAR(20) DEFAULT 'USUARIO'
);

CREATE TABLE Evento(
    ID_EVENTO BIGINT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    DESCRICAO VARCHAR(500) NULL,
    DATA_EVENTO TIMESTAMP NOT NULL,
    LOCAL VARCHAR(200) NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE ingresso(
    ID_INGRESSO BIGINT PRIMARY KEY,
    ID_EVENTO BIGINT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL,
    ID_USUARIO INT NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CONSTRAINT fk_ingresso_usuario FOREIGN KEY (ID_USUARIO) REFERENCES Usuario (ID_USUARIO),
    CONSTRAINT fk_ingresso_evento FOREIGN KEY (ID_EVENTO) REFERENCES evento (ID_EVENTO)
);

CREATE TABLE Gameficador(
    ID_GAMEFICADOR BIGINT PRIMARY KEY,
    ID_USUARIO BIGINT NOT NULL,
    PONTUACAO INT DEFAULT 0,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_gameficador_usuario FOREIGN KEY (ID_USUARIO) REFERENCES Usuario (ID_USUARIO)
);