// <auto-generated />
using System;
using CardGameStore.Multitenancy;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardGameStore.Data.Migrations.Catalog
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260812124206_AddLeadAttributionAndPrivacyGovernance")]
    partial class AddLeadAttributionAndPrivacyGovernance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardGameStore.Multitenancy.ContadorAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_token_expiry");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_contador_accounts_email");

                    b.ToTable("contador_accounts");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ContadorAviso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("autor");

                    b.Property<Guid>("ContadorTenantLinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("contador_tenant_link_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.HasKey("Id");

                    b.HasIndex("ContadorTenantLinkId")
                        .HasDatabaseName("ix_contador_avisos_link_id");

                    b.ToTable("contador_avisos");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ContadorConviteEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("Email", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_contador_convites_email_pair");

                    b.ToTable("contador_convites_email");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ContadorTenantLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContadorAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("contador_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ContadorAccountId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_contador_tenant_links_pair");

                    b.ToTable("contador_tenant_links");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.CrmActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by_user_name");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<string>("Outcome")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("outcome");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("CompletedAt", "DueAt")
                        .HasDatabaseName("ix_crm_activities_open_due");

                    b.HasIndex("LeadId", "CreatedAt")
                        .HasDatabaseName("ix_crm_activities_lead_date");

                    b.ToTable("crm_activities");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.CrmOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<string>("AssignedUserName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("assigned_user_name");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpectedCloseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_close_date");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("LostReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("lost_reason");

                    b.Property<int>("Probability")
                        .HasColumnType("integer")
                        .HasColumnName("probability");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("stage");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ExpectedCloseDate")
                        .HasDatabaseName("ix_crm_opportunities_expected_close");

                    b.HasIndex("LeadId")
                        .IsUnique()
                        .HasDatabaseName("ix_crm_opportunities_lead_unique");

                    b.HasIndex("Stage", "AssignedUserId")
                        .HasDatabaseName("ix_crm_opportunities_stage_owner");

                    b.ToTable("crm_opportunities");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AbordagemSugerida")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("abordagem_sugerida");

                    b.Property<string>("Campaign")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("campaign");

                    b.Property<Guid?>("ConvertedTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_tenant_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataOriginDetails")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("data_origin_details");

                    b.Property<string>("DigitalPresence")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("digital_presence");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("EstimatedRevenueRange")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("estimated_revenue_range");

                    b.Property<string>("LandingPage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("landing_page");

                    b.Property<string>("LegalBasis")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("legal_basis");

                    b.Property<DateTime?>("LegitimateInterestAssessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("legitimate_interest_assessed_at");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("mensagem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notas");

                    b.Property<int?>("OpportunityScore")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_score");

                    b.Property<DateTime?>("OpposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opposed_at");

                    b.Property<string>("OppositionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("opposition_reason");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("origem");

                    b.Property<string>("PlaceId")
                        .HasColumnType("text")
                        .HasColumnName("place_id");

                    b.Property<DateTime?>("PrivacyNoticeAcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("privacy_notice_acknowledged_at");

                    b.Property<string>("PrivacyNoticeVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("privacy_notice_version");

                    b.Property<string>("ProcessingPurpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("processing_purpose");

                    b.Property<Guid?>("ReferralPartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("referral_partner_id");

                    b.Property<string>("ReferrerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("referrer_url");

                    b.Property<DateTime?>("RetentionReviewAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retention_review_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("utm_campaign");

                    b.Property<string>("UtmContent")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("utm_content");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("utm_medium");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("utm_source");

                    b.Property<string>("UtmTerm")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("utm_term");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_leads_created_at");

                    b.HasIndex("PlaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_leads_place_id_unique")
                        .HasFilter("place_id IS NOT NULL");

                    b.HasIndex("ReferralPartnerId")
                        .HasDatabaseName("ix_leads_referral_partner_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_leads_status");

                    b.ToTable("leads");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.LoginRedirectTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_kind");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TenantSlug")
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("tenant_slug");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ticket");

                    b.HasKey("Id");

                    b.HasIndex("Ticket")
                        .IsUnique()
                        .HasDatabaseName("ix_login_redirect_tickets_ticket");

                    b.ToTable("login_redirect_tickets");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.PlatformImpersonationTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("PlatformOwnerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("platform_owner_name");

                    b.Property<Guid>("PlatformOwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("platform_owner_user_id");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TenantSlug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("tenant_slug");

                    b.Property<string>("Ticket")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ticket");

                    b.HasKey("Id");

                    b.HasIndex("Ticket")
                        .IsUnique()
                        .HasDatabaseName("ix_platform_impersonation_tickets_ticket");

                    b.ToTable("platform_impersonation_tickets");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ProspectCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("DigitalPresence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("digital_presence");

                    b.Property<int?>("EnrichmentConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("enrichment_confidence");

                    b.Property<string>("EnrichmentSource")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("enrichment_source");

                    b.Property<string>("EnrichmentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("enrichment_status");

                    b.Property<string>("EstimatedRevenueRange")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("estimated_revenue_range");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTime?>("LastEnrichedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_enriched_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("OpportunityScore")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_score");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<Guid>("SearchId")
                        .HasColumnType("uuid")
                        .HasColumnName("search_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedApproach")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("suggested_approach");

                    b.Property<string>("Website")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("ix_prospect_candidates_lead_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_prospect_candidates_status");

                    b.HasIndex("SearchId", "Source", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_prospect_candidates_search_source_unique");

                    b.ToTable("prospect_candidates");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ProspectObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_id");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("field_name");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("ObservedValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observed_value");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("previous_value");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "ObservedAt")
                        .HasDatabaseName("ix_prospect_observations_candidate_date");

                    b.ToTable("prospect_observations");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ProspectSuppression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("key_type");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("normalized_value");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("KeyType", "NormalizedValue")
                        .IsUnique()
                        .HasDatabaseName("ix_prospect_suppressions_key_unique");

                    b.ToTable("prospect_suppressions");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ProspectingCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyRunBudget")
                        .HasColumnType("integer")
                        .HasColumnName("daily_run_budget");

                    b.Property<int>("IntervalHours")
                        .HasColumnType("integer")
                        .HasColumnName("interval_hours");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<int>("MaxCandidatesPerRun")
                        .HasColumnType("integer")
                        .HasColumnName("max_candidates_per_run");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_retry_attempts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTime>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextRunAt")
                        .HasDatabaseName("ix_prospecting_campaigns_due");

                    b.ToTable("prospecting_campaigns");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ProspectingCampaignRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DiscoveredCount")
                        .HasColumnType("integer")
                        .HasColumnName("discovered_count");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error");

                    b.Property<int>("NewCount")
                        .HasColumnType("integer")
                        .HasColumnName("new_count");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid?>("SearchId")
                        .HasColumnType("uuid")
                        .HasColumnName("search_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique()
                        .HasDatabaseName("ix_prospecting_campaign_runs_active_unique")
                        .HasFilter("\"status\" IN ('Queued', 'Running')");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_prospecting_campaign_runs_queue");

                    b.ToTable("prospecting_campaign_runs");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ProspectingSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("cache_key");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("East")
                        .HasColumnType("double precision")
                        .HasColumnName("east");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<double>("North")
                        .HasColumnType("double precision")
                        .HasColumnName("north");

                    b.Property<long?>("OsmAreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("osm_area_id");

                    b.Property<DateTime>("RefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refreshed_at");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<double>("South")
                        .HasColumnType("double precision")
                        .HasColumnName("south");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Warning")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("warning");

                    b.Property<double>("West")
                        .HasColumnType("double precision")
                        .HasColumnName("west");

                    b.HasKey("Id");

                    b.HasIndex("CacheKey")
                        .IsUnique()
                        .HasDatabaseName("ix_prospecting_searches_cache_key");

                    b.HasIndex("RefreshedAt")
                        .HasDatabaseName("ix_prospecting_searches_refreshed_at");

                    b.ToTable("prospecting_searches");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ReferralCommission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("base_amount");

                    b.Property<string>("ChargeKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("charge_kind");

                    b.Property<decimal>("CommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("commission_percent");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<DateTime>("ReferenceMonth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reference_month");

                    b.Property<Guid>("ReferralId")
                        .HasColumnType("uuid")
                        .HasColumnName("referral_id");

                    b.Property<Guid>("TenantChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_charge_id");

                    b.HasKey("Id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_referral_commissions_due_date");

                    b.HasIndex("ReferenceMonth")
                        .HasDatabaseName("ix_referral_commissions_reference_month");

                    b.HasIndex("ReferralId");

                    b.HasIndex("TenantChargeId")
                        .IsUnique()
                        .HasDatabaseName("ix_referral_commissions_charge_unique");

                    b.ToTable("referral_commissions");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ReferralPartner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Document")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("document");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<decimal>("MonthlyCommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("monthly_commission_percent");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("PaymentDay")
                        .HasColumnType("integer")
                        .HasColumnName("payment_day");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("PixKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pix_key");

                    b.Property<decimal>("SetupCommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("setup_commission_percent");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Document")
                        .IsUnique()
                        .HasDatabaseName("ix_referral_partners_document_unique")
                        .HasFilter("document IS NOT NULL");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_referral_partners_name");

                    b.ToTable("referral_partners");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by_user_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_support_tickets_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_support_tickets_tenant_id");

                    b.ToTable("support_tickets");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.SupportTicketMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("author_name");

                    b.Property<string>("AuthorRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("author_role");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_support_ticket_messages_ticket_id");

                    b.ToTable("support_ticket_messages");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BillingStartsOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("billing_starts_on");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("custom_domain");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string[]>("EnabledModules")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("enabled_modules");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("logo_url");

                    b.Property<int?>("MaxUsers")
                        .HasColumnType("integer")
                        .HasColumnName("max_users");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monthly_price");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("payment_status");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("plan_name");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("schema_name");

                    b.Property<decimal>("SetupFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("setup_fee");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CustomDomain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_custom_domain")
                        .HasFilter("custom_domain IS NOT NULL");

                    b.HasIndex("SchemaName")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_schema_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.TenantCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<DateTime>("ReferenceMonth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reference_month");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_tenant_charges_due_date");

                    b.HasIndex("ReferenceMonth")
                        .HasDatabaseName("ix_tenant_charges_reference_month");

                    b.HasIndex("TenantId", "Kind", "ReferenceMonth")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_charges_tenant_kind_competencia");

                    b.ToTable("tenant_charges");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.TenantReferral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("MonthlyCommissionCycles")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_commission_cycles");

                    b.Property<decimal>("MonthlyCommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("monthly_commission_percent");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<decimal>("SetupCommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("setup_commission_percent");

                    b.Property<Guid?>("SourceLeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_lead_id");

                    b.Property<DateTime>("StartedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_on");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("ix_tenant_referrals_partner_id");

                    b.HasIndex("SourceLeadId");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_referrals_tenant_unique");

                    b.ToTable("tenant_referrals");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ContadorAviso", b =>
                {
                    b.HasOne("CardGameStore.Multitenancy.ContadorTenantLink", null)
                        .WithMany()
                        .HasForeignKey("ContadorTenantLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ContadorConviteEmail", b =>
                {
                    b.HasOne("CardGameStore.Multitenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ContadorTenantLink", b =>
                {
                    b.HasOne("CardGameStore.Multitenancy.ContadorAccount", null)
                        .WithMany()
                        .HasForeignKey("ContadorAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardGameStore.Multitenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.CrmActivity", b =>
                {
                    b.HasOne("CardGameStore.Multitenancy.Lead", "Lead")
                        .WithMany("Activities")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardGameStore.Multitenancy.CrmOpportunity", "Opportunity")
                        .WithMany("Activities")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lead");

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.CrmOpportunity", b =>
                {
                    b.HasOne("CardGameStore.Multitenancy.Lead", "Lead")
                        .WithOne("Opportunity")
                        .HasForeignKey("CardGameStore.Multitenancy.CrmOpportunity", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.Lead", b =>
                {
                    b.HasOne("CardGameStore.Multitenancy.ReferralPartner", null)
                        .WithMany()
                        .HasForeignKey("ReferralPartnerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ProspectCandidate", b =>
                {
                    b.HasOne("CardGameStore.Multitenancy.ProspectingSearch", "Search")
                        .WithMany("Candidates")
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Search");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ProspectObservation", b =>
                {
                    b.HasOne("CardGameStore.Multitenancy.ProspectCandidate", "Candidate")
                        .WithMany("Observations")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ProspectingCampaignRun", b =>
                {
                    b.HasOne("CardGameStore.Multitenancy.ProspectingCampaign", "Campaign")
                        .WithMany("Runs")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ReferralCommission", b =>
                {
                    b.HasOne("CardGameStore.Multitenancy.TenantReferral", null)
                        .WithMany()
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardGameStore.Multitenancy.TenantCharge", null)
                        .WithMany()
                        .HasForeignKey("TenantChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.SupportTicketMessage", b =>
                {
                    b.HasOne("CardGameStore.Multitenancy.SupportTicket", null)
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.TenantCharge", b =>
                {
                    b.HasOne("CardGameStore.Multitenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.TenantReferral", b =>
                {
                    b.HasOne("CardGameStore.Multitenancy.ReferralPartner", null)
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CardGameStore.Multitenancy.Lead", null)
                        .WithMany()
                        .HasForeignKey("SourceLeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CardGameStore.Multitenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.CrmOpportunity", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.Lead", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ProspectCandidate", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ProspectingCampaign", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.ProspectingSearch", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("CardGameStore.Multitenancy.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
