import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalActions } from '@/components/LegalActions'

export const metadata: Metadata = {
  title: 'Política de Privacidade',
  description: 'Como a plataforma multiempresa Octus trata e protege dados pessoais conforme a LGPD.',
  alternates: { canonical: '/privacidade' },
}

export default function PrivacidadePage() {
  return (
    <main className="min-h-screen bg-[#f7fbfd] text-[#22384A]">
      <header className="bg-[#0C3D5A] px-4 py-5 text-white print:hidden"><div className="mx-auto flex max-w-4xl items-center justify-between"><Link href="/" className="text-xl font-black">Octus</Link><LegalActions /></div></header>
      <article className="mx-auto max-w-4xl px-4 py-12">
        <p className="text-xs font-bold uppercase tracking-widest text-brand-700">LGPD · transparência multiempresa</p>
        <h1 className="mt-2 text-3xl font-black text-[#0C3D5A]">Política de Privacidade</h1>
        <p className="mt-2 text-sm text-[#6B8598]">Versão 2.1 · atualizada em 12 de agosto de 2026</p>
        <div className="mt-8 space-y-3">
          <Notice>Esta política explica o tratamento realizado pela plataforma Octus. O estabelecimento cuja marca ou domínio você acessou pode fornecer aviso complementar, pois define as finalidades comerciais relacionadas a seus clientes.</Notice>
          <Section title="1. Papéis e responsáveis"><p>A <strong>3E Systen</strong> fornece o Octus. Para dados de clientes, vendas, comandas e atendimento, o Estabelecimento normalmente atua como <strong>controlador</strong> e a 3E Systen como <strong>operadora</strong>. Para segurança da plataforma, contratação, suporte e melhoria autorizada, cada parte poderá controlar os tratamentos que efetivamente decidir.</p></Section>
          <Section title="2. Dados tratados"><p>Podemos tratar cadastro e contato (nome, CPF, telefone e e-mail), credenciais e permissões, empresa/CNPJ, dados de pedidos, comandas, pagamentos e crediário, documentos e configurações fiscais, interações de suporte, registros técnicos, dispositivo, data e hora, além de IP protegido por hash nos registros em que essa técnica é aplicável.</p><p>No relacionamento comercial também registramos a origem profissional pública do potencial cliente, campanha, parâmetros UTM, página de entrada, referência, vendedor indicador, histórico de interações, avaliação de oportunidade e decisões de privacidade. Não buscamos dados sensíveis para prospecção.</p><p>Dados bancários e fiscais só são usados nos recursos escolhidos. Senhas, certificados e segredos recebem controles próprios; não solicitamos que sejam enviados por canais informais.</p></Section>
          <Section title="3. Finalidades e bases legais"><p>Tratamos dados para executar contratos e funcionalidades solicitadas; autenticar usuários; processar operações; cumprir obrigações legais e fiscais; prevenir fraude e incidentes; atender suporte e direitos dos titulares; exercer direitos em processos; e, quando autorizado, medir desempenho ou enviar comunicações opcionais.</p><p>Quando você envia o formulário comercial, usamos os dados para responder à sua solicitação e realizar procedimentos relacionados a uma possível contratação. A marcação de ciência comprova que este aviso foi apresentado e não é usada como autorização genérica para marketing.</p><p>Na prospecção empresarial, podem ser usados dados profissionais tornados públicos para identificar negócios potencialmente compatíveis. Antes do contato ativo, registramos finalidade, necessidade, origem e avaliação de legítimo interesse; respeitamos a expectativa do titular, usamos apenas dados pertinentes e bloqueamos novos contatos quando houver oposição. O legítimo interesse não é usado pelo módulo para dados sensíveis.</p><p>As bases podem incluir execução de contrato, procedimentos preliminares, obrigação legal ou regulatória, exercício regular de direitos, legítimo interesse após avaliação aplicável e consentimento para finalidades opcionais. A base depende do contexto, não do simples tipo do dado.</p></Section>
          <Section title="4. Compartilhamento e integrações"><p>Dados podem ser compartilhados, no mínimo necessário, com infraestrutura de hospedagem e banco de dados, provedores de e-mail, bancos, meios de pagamento, serviços fiscais, contadores autorizados, suporte técnico e o serviço público VLibras quando o recurso de acessibilidade estiver habilitado, conforme os módulos usados. Também podemos atender ordem de autoridade competente. Não vendemos dados pessoais.</p><p>Integrações ativadas pelo Estabelecimento têm condições próprias. Transferências internacionais, quando existentes em infraestrutura contratada, devem observar salvaguardas compatíveis com a LGPD.</p></Section>
          <Section title="5. Cookies e análise"><p>Tecnologias necessárias mantêm autenticação, segurança, preferências e funcionamento. Análise e marketing permanecem opcionais e dependem da escolha registrada no navegador. Categorias, controles e prazos são detalhados na <Link href="/cookies">Política de Cookies</Link>.</p></Section>
          <Section title="6. Retenção e eliminação"><p>Dados são mantidos enquanto necessários à conta, ao contrato e às finalidades informadas, e depois pelo período exigido para obrigações fiscais, contábeis, segurança e defesa de direitos. Ao fim, são eliminados ou anonimizados, ressalvadas hipóteses legais. Backups seguem ciclo técnico de substituição e acesso restrito.</p><p>Leads sem conversão recebem uma revisão de necessidade em até 180 dias. A data é um controle de revisão, não autorização para retenção automática: o registro deve ser eliminado, anonimizado ou ter sua necessidade justificada. Oposição bloqueia imediatamente novos contatos, preservando-se somente o mínimo necessário para comprovar e respeitar o bloqueio.</p></Section>
          <Section title="7. Segurança"><p>Aplicamos isolamento por empresa, controle de acesso e permissões, criptografia em trânsito, proteção de credenciais, auditoria, limitação de requisições, cópias de segurança e monitoramento proporcional ao risco. Nenhum sistema é infalível; incidentes confirmados são avaliados e comunicados quando exigido.</p></Section>
          <Section title="8. Direitos dos titulares"><p>Você pode solicitar confirmação e acesso, correção, anonimização, bloqueio ou eliminação quando cabível, portabilidade conforme regulamentação, informação sobre compartilhamento, oposição, revisão de decisões automatizadas e revogação do consentimento. A identidade poderá ser verificada para evitar entrega indevida.</p><p>Use o <Link href="/lgpd">portal de direitos LGPD</Link>. Quando o pedido se referir a uma compra ou cadastro, o Estabelecimento poderá ser o responsável pela resposta; o Octus apoiará tecnicamente quando atuar como operador.</p></Section>
          <Section title="9. Crianças e adolescentes"><p>O serviço empresarial não é direcionado a crianças para contratação autônoma. Estabelecimentos que tratem dados de crianças ou adolescentes devem observar seu melhor interesse, a base legal adequada e os deveres de transparência e representação aplicáveis.</p></Section>
          <Section title="10. Contato e alterações"><p>Contato de privacidade da plataforma: <a href="mailto:3esysten@gmail.com">3esysten@gmail.com</a>. O Estabelecimento pode indicar canal próprio na interface. Se a resposta não resolver a questão, o titular pode procurar a Autoridade Nacional de Proteção de Dados ou órgãos de defesa do consumidor competentes.</p><p>Alterações relevantes terão nova versão, data e comunicação apropriada. Uma nova finalidade incompatível será submetida à base legal e à transparência necessárias; o simples uso continuado não substitui consentimento quando ele for exigido.</p></Section>
        </div>
        <nav className="mt-10 flex flex-wrap gap-4 border-t border-[#0C3D5A]/10 pt-6 text-sm font-semibold text-brand-700"><Link href="/termos">Termos</Link><Link href="/cookies">Cookies</Link><Link href="/lgpd">Direitos LGPD</Link></nav>
      </article>
    </main>
  )
}

function Notice({ children }: { children: React.ReactNode }) { return <div className="rounded-2xl border border-brand-200 bg-brand-50 p-5 text-sm leading-relaxed">{children}</div> }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-[#0C3D5A]/10 bg-white p-5 sm:p-6"><h2 className="font-bold text-[#0C3D5A]">{title}</h2><div className="mt-3 space-y-3 text-sm leading-relaxed text-[#526E80] [&_a]:font-semibold [&_a]:text-brand-700 [&_a]:underline">{children}</div></section> }
