// =============================================================================
// CondicoesComerciaisSincronizacaoTests.cs — Negociar e ver as cobranças
// acompanharem: gerador mensal, recálculo depois de mudar as condições, e o
// cancelamento da fatura no gateway quando o valor dela muda.
//
// O que se protege: fatura antiga continuar valendo depois da renegociação
// (dois valores pra mesma dívida), renegociação perdoando dívida passada,
// parcela paga sendo recalculada, e ajuste manual sendo atropelado.
//
// InMemory, como os outros testes de billing. As competências são relativas a
// hoje porque o recálculo só mexe da competência atual em diante.
// =============================================================================

using System.Text.Json;
using CardGameStore.DTOs;
using CardGameStore.Multitenancy;
using CardGameStore.Services.Implementations;
using CardGameStore.Services.Interfaces;
using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Xunit;

namespace CardGameStore.Tests.Services;

public class CondicoesComerciaisSincronizacaoTests
{
    private static readonly DateTime MesAtual =
        new(DateTime.UtcNow.Year, DateTime.UtcNow.Month, 1, 0, 0, 0, DateTimeKind.Utc);

    private static CatalogDbContext CreateDb() =>
        new(new DbContextOptionsBuilder<CatalogDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);

    private static (PlatformBillingService Billing, CondicoesComerciaisService Condicoes) Servicos(
        CatalogDbContext db, IPlatformPaymentGateway? gateway = null)
    {
        var billing = new PlatformBillingService(db, NullLogger<PlatformBillingService>.Instance, gateway: gateway);
        return (billing, new CondicoesComerciaisService(db, billing));
    }

    /// <summary>Loja cobrando há dois meses, vencimento dia 10.</summary>
    private static async Task<Tenant> LojaAsync(CatalogDbContext db, decimal mensalidade = 200m)
    {
        var tenant = new Tenant
        {
            Slug = "loja-negociada", SchemaName = "tenant_loja_negociada", Status = TenantStatus.Active,
            MonthlyPrice = mensalidade, BillingStartsOn = MesAtual.AddMonths(-2).AddDays(9),
        };
        db.Tenants.Add(tenant);
        await db.SaveChangesAsync();
        return tenant;
    }

    private static AtualizarCondicoesRequest Condicoes(Tenant t, Action<AtualizarCondicoesRequest>? ajuste = null)
    {
        var request = new AtualizarCondicoesRequest
        {
            Mensalidade                   = t.MonthlyPrice,
            InicioCobranca                = t.BillingStartsOn,
            DiaVencimento                 = t.BillingDueDay,
            ImplantacaoValor              = t.SetupFee,
            ImplantacaoParcelas           = t.SetupInstallments,
            ImplantacaoPrimeiroVencimento = t.SetupFirstDueDate,
        };
        ajuste?.Invoke(request);
        return request;
    }

    private static SalvarDescontoRequest Desconto(string tipo, decimal valor, DateTime inicio, DateTime? fim = null) =>
        new() { Descricao = "Parceiro", Tipo = tipo, Valor = valor, CompetenciaInicial = inicio, CompetenciaFinal = fim };

    // ── Gerador ──────────────────────────────────────────────────────────────

    [Fact]
    public async Task Gerador_AplicaDescontoVigenteERegistraOQueEntrou()
    {
        using var db = CreateDb();
        var tenant = await LojaAsync(db);
        var (billing, condicoes) = Servicos(db);
        await condicoes.CriarDescontoAsync(tenant.Id, Desconto("Percentual", 10m, MesAtual), "Taino");

        var cobranca = await db.TenantCharges.SingleAsync(c => c.ReferenceMonth == MesAtual);

        cobranca.Amount.Should().Be(180m);
        cobranca.GrossAmount.Should().Be(200m);
        cobranca.DiscountAmount.Should().Be(20m);
        cobranca.DiscountSummary.Should().Be("Parceiro 10%");
        cobranca.AutoGenerated.Should().BeTrue();

        // Rodar o gerador do mês de novo não duplica o que o recálculo já criou.
        (await billing.GerarMensalidadesAsync(MesAtual)).Criadas.Should().Be(0);
    }

    [Fact]
    public async Task Gerador_DescontoIntegral_NaoCriaCobrancaDeZero()
    {
        using var db = CreateDb();
        var tenant = await LojaAsync(db);
        db.TenantBillingDiscounts.Add(new TenantBillingDiscount
        {
            TenantId = tenant.Id, Description = "Cortesia", Kind = TenantDiscountKind.Percentual,
            Value = 100m, StartMonth = MesAtual,
        });
        await db.SaveChangesAsync();

        var resultado = await Servicos(db).Billing.GerarMensalidadesAsync(MesAtual);

        resultado.Criadas.Should().Be(0);
        resultado.ZeradasPorDesconto.Should().Be(1);
    }

    [Fact]
    public async Task Gerador_ImplantacaoParcelada_CriaUmaParcelaPorMes()
    {
        using var db = CreateDb();
        var tenant = await LojaAsync(db, mensalidade: 0m);
        tenant.SetupFee = 900m;
        tenant.SetupInstallments = 3;
        tenant.SetupFirstDueDate = MesAtual.AddDays(14);
        await db.SaveChangesAsync();

        var (billing, _) = Servicos(db);

        await billing.GerarMensalidadesAsync(MesAtual);
        var parcelas = await db.TenantCharges.Where(c => c.Kind == TenantChargeKind.Implantacao).ToListAsync();
        parcelas.Should().ContainSingle().Which.InstallmentNumber.Should().Be(1,
            "a parcela do mês seguinte não pode ir ao gateway antes da hora");

        await billing.GerarMensalidadesAsync(MesAtual.AddMonths(1));
        await billing.GerarMensalidadesAsync(MesAtual.AddMonths(2));
        await billing.GerarMensalidadesAsync(MesAtual.AddMonths(3));

        var todas = await db.TenantCharges.Where(c => c.Kind == TenantChargeKind.Implantacao)
            .OrderBy(c => c.InstallmentNumber).ToListAsync();
        todas.Select(c => c.Amount).Should().Equal(300m, 300m, 300m);
        todas.Select(c => c.DueDate.Day).Should().OnlyContain(d => d == 15);
    }

    [Fact]
    public async Task Gerador_ImplantacaoLancadaAMao_NaoGeraParcelasPorCima()
    {
        using var db = CreateDb();
        var tenant = await LojaAsync(db, mensalidade: 0m);
        tenant.SetupFee = 900m;
        tenant.SetupInstallments = 3;
        tenant.SetupFirstDueDate = MesAtual.AddDays(14);
        db.TenantCharges.Add(new TenantCharge
        {
            TenantId = tenant.Id, Kind = TenantChargeKind.Implantacao, Amount = 900m,
            ReferenceMonth = MesAtual.AddMonths(-2), DueDate = MesAtual.AddMonths(-2),
        });
        await db.SaveChangesAsync();

        await Servicos(db).Billing.GerarMensalidadesAsync(MesAtual);

        (await db.TenantCharges.CountAsync()).Should().Be(1, "cobraria a implantação duas vezes");
    }

    // ── Recálculo ────────────────────────────────────────────────────────────

    [Fact]
    public async Task Renegociacao_FaturaEmitida_EhCanceladaNoGatewayEVoltaParaEmissao()
    {
        using var db = CreateDb();
        var tenant = await LojaAsync(db);
        var gateway = new GatewayFalso();
        var (billing, condicoes) = Servicos(db, gateway);
        await billing.GerarMensalidadesAsync(MesAtual);

        var cobranca = await db.TenantCharges.SingleAsync();
        cobranca.Gateway = gateway.Name;
        cobranca.ExternalChargeId = "pay_antiga";
        cobranca.PaymentUrl = "https://asaas.test/pay_antiga";
        await db.SaveChangesAsync();

        var resultado = await condicoes.CriarDescontoAsync(tenant.Id, Desconto("ValorFixo", 50m, MesAtual), null);

        resultado.Cobrancas.Atualizadas.Should().Be(1);
        resultado.Cobrancas.Pendencias.Should().BeEmpty();
        gateway.Canceladas.Should().Equal("pay_antiga");

        var atualizada = await db.TenantCharges.AsNoTracking().SingleAsync();
        atualizada.Amount.Should().Be(150m);
        atualizada.ExternalChargeId.Should().BeNull("sem id externo, a próxima rodada reemite com o valor novo");
        atualizada.PaymentUrl.Should().BeNull();
    }

    [Fact]
    public async Task Renegociacao_GatewayRecusaCancelar_NaoMexeNaCobranca()
    {
        using var db = CreateDb();
        var tenant = await LojaAsync(db);
        var gateway = new GatewayFalso { RecusarCancelamento = true };
        var (billing, condicoes) = Servicos(db, gateway);
        await billing.GerarMensalidadesAsync(MesAtual);

        var cobranca = await db.TenantCharges.SingleAsync();
        cobranca.Gateway = gateway.Name;
        cobranca.ExternalChargeId = "pay_paga_la";
        await db.SaveChangesAsync();

        var resultado = await condicoes.CriarDescontoAsync(tenant.Id, Desconto("ValorFixo", 50m, MesAtual), null);

        resultado.Cobrancas.Atualizadas.Should().Be(0);
        resultado.Cobrancas.Pendencias.Should().ContainSingle().Which.Should().Contain("Nada foi alterado");

        var intacta = await db.TenantCharges.AsNoTracking().SingleAsync();
        intacta.Amount.Should().Be(200m, "a fatura continua valendo na mão do lojista");
        intacta.ExternalChargeId.Should().Be("pay_paga_la");
    }

    [Fact]
    public async Task Renegociacao_NaoPerdoaDividaDeCompetenciaPassada()
    {
        using var db = CreateDb();
        var tenant = await LojaAsync(db);
        var (billing, condicoes) = Servicos(db);
        await billing.GerarMensalidadesAsync(MesAtual.AddMonths(-1));

        await condicoes.AtualizarAsync(tenant.Id, Condicoes(tenant, r => r.Mensalidade = 99m));

        var passada = await db.TenantCharges.AsNoTracking().SingleAsync(c => c.ReferenceMonth == MesAtual.AddMonths(-1));
        passada.Amount.Should().Be(200m);

        var atual = await db.TenantCharges.AsNoTracking().SingleAsync(c => c.ReferenceMonth == MesAtual);
        atual.Amount.Should().Be(99m);
    }

    [Fact]
    public async Task Renegociacao_NaoAtropelaCobrancaAjustadaAMao()
    {
        using var db = CreateDb();
        var tenant = await LojaAsync(db);
        var (billing, condicoes) = Servicos(db);
        await billing.GerarMensalidadesAsync(MesAtual);

        var cobranca = await db.TenantCharges.SingleAsync();
        await billing.AtualizarCobrancaAsync(cobranca.Id, new AtualizarCobrancaRequest { Valor = 120m, Vencimento = cobranca.DueDate });

        await condicoes.CriarDescontoAsync(tenant.Id, Desconto("Percentual", 10m, MesAtual), null);

        (await db.TenantCharges.AsNoTracking().SingleAsync()).Amount.Should().Be(120m);
    }

    [Fact]
    public async Task Renegociacao_DiaDeVencimento_MoveACobrancaEmAberto()
    {
        using var db = CreateDb();
        var tenant = await LojaAsync(db);
        var (billing, condicoes) = Servicos(db);
        await billing.GerarMensalidadesAsync(MesAtual);

        await condicoes.AtualizarAsync(tenant.Id, Condicoes(tenant, r => r.DiaVencimento = 25));

        (await db.TenantCharges.AsNoTracking().SingleAsync()).DueDate.Day.Should().Be(25);
    }

    [Fact]
    public async Task Renegociacao_MenosParcelas_RedistribuiERemoveASobra()
    {
        using var db = CreateDb();
        var tenant = await LojaAsync(db, mensalidade: 0m);
        var (billing, condicoes) = Servicos(db);

        // 4 parcelas a partir do mês passado: a 1ª já foi paga, a 2ª (deste mês) está em aberto.
        tenant.SetupFee = 400m;
        tenant.SetupInstallments = 4;
        tenant.SetupFirstDueDate = MesAtual.AddMonths(-1).AddDays(4);
        await db.SaveChangesAsync();
        await billing.GerarMensalidadesAsync(MesAtual);

        var primeira = await db.TenantCharges.SingleAsync(c => c.InstallmentNumber == 1);
        primeira.PaidAt = MesAtual.AddMonths(-1).AddDays(4);
        await db.SaveChangesAsync();

        var resultado = await condicoes.AtualizarAsync(tenant.Id, Condicoes(tenant, r => r.ImplantacaoParcelas = 2));

        resultado.Cobrancas.Pendencias.Should().BeEmpty();
        var parcelas = await db.TenantCharges.AsNoTracking().OrderBy(c => c.InstallmentNumber).ToListAsync();
        parcelas.Select(c => (c.InstallmentNumber!.Value, c.Amount, c.InstallmentCount!.Value))
            .Should().Equal((1, 100m, 4), (2, 300m, 2));
    }

    [Fact]
    public async Task Renegociacao_ImplantacaoAbaixoDoJaPago_EhRecusada()
    {
        using var db = CreateDb();
        var tenant = await LojaAsync(db, mensalidade: 0m);
        tenant.SetupFee = 400m;
        tenant.SetupInstallments = 2;
        tenant.SetupFirstDueDate = MesAtual.AddDays(4);
        db.TenantCharges.Add(new TenantCharge
        {
            TenantId = tenant.Id, Kind = TenantChargeKind.Implantacao, Amount = 200m, InstallmentNumber = 1,
            InstallmentCount = 2, ReferenceMonth = MesAtual, DueDate = MesAtual.AddDays(4),
            PaidAt = MesAtual.AddDays(1), AutoGenerated = true,
        });
        await db.SaveChangesAsync();

        var acao = () => Servicos(db).Condicoes.AtualizarAsync(tenant.Id, Condicoes(tenant, r => r.ImplantacaoValor = 150m));

        await acao.Should().ThrowAsync<InvalidOperationException>().WithMessage("*já foram pagos*");
    }

    [Fact]
    public async Task Previa_MostraDescontoAcabandoEParcelas()
    {
        using var db = CreateDb();
        var tenant = await LojaAsync(db);
        tenant.SetupFee = 300m;
        tenant.SetupInstallments = 3;
        tenant.SetupFirstDueDate = MesAtual.AddMonths(1).AddDays(4);
        await db.SaveChangesAsync();

        var condicoes = Servicos(db).Condicoes;
        var dto = (await condicoes.CriarDescontoAsync(tenant.Id,
            Desconto("ValorFixo", 50m, MesAtual, MesAtual.AddMonths(1)), "Taino")).Condicoes;

        dto.Previa.Should().HaveCount(12);
        dto.Previa[0].Itens.Should().ContainSingle(i => i.Tipo == "Mensalidade").Which.Situacao.Should().Be("EmAberto");
        dto.Previa[0].Total.Should().Be(150m);
        dto.Previa[1].Total.Should().Be(150m + 100m, "último mês do desconto e primeira parcela");
        dto.Previa[2].Total.Should().Be(200m + 100m);
        dto.Previa[4].Total.Should().Be(200m);
        dto.Descontos.Should().ContainSingle().Which.CriadoPor.Should().Be("Taino");
    }

    // ── Exclusão manual ──────────────────────────────────────────────────────

    [Fact]
    public async Task ExcluirMensalidadeDoMes_QueSeriaRecriada_EhRecusada()
    {
        using var db = CreateDb();
        await LojaAsync(db);
        var billing = Servicos(db).Billing;
        await billing.GerarMensalidadesAsync(MesAtual);

        var cobranca = await db.TenantCharges.SingleAsync();
        var acao = () => billing.ExcluirCobrancaAsync(cobranca.Id);

        await acao.Should().ThrowAsync<InvalidOperationException>().WithMessage("*seria gerada de novo*");
    }

    [Fact]
    public async Task ExcluirCobrancaEmitida_CancelaNoGatewayAntes()
    {
        using var db = CreateDb();
        var tenant = await LojaAsync(db);
        var gateway = new GatewayFalso();
        db.TenantCharges.Add(new TenantCharge
        {
            TenantId = tenant.Id, Kind = TenantChargeKind.Mensalidade, Amount = 200m,
            ReferenceMonth = MesAtual.AddMonths(-1), DueDate = MesAtual.AddMonths(-1).AddDays(9),
            Gateway = gateway.Name, ExternalChargeId = "pay_mes_passado",
        });
        await db.SaveChangesAsync();

        var cobranca = await db.TenantCharges.SingleAsync();
        await Servicos(db, gateway).Billing.ExcluirCobrancaAsync(cobranca.Id);

        gateway.Canceladas.Should().Equal("pay_mes_passado");
        (await db.TenantCharges.AnyAsync()).Should().BeFalse();
    }

    private sealed class GatewayFalso : IPlatformPaymentGateway
    {
        public bool RecusarCancelamento { get; init; }
        public List<string> Canceladas { get; } = new();

        public string Name => "teste";
        public bool IsConfigured => true;

        public Task<string> GarantirClienteAsync(Tenant tenant, CancellationToken ct = default) => Task.FromResult("cus_teste");

        public Task<CobrancaGatewayResult> EmitirCobrancaAsync(TenantCharge charge, Tenant tenant, CancellationToken ct = default) =>
            Task.FromResult(new CobrancaGatewayResult($"pay_{charge.Id:N}", null));

        public Task CancelarCobrancaAsync(string externalChargeId, CancellationToken ct = default)
        {
            if (RecusarCancelamento) throw new InvalidOperationException("Asaas recusou o cancelamento (400).");
            Canceladas.Add(externalChargeId);
            return Task.CompletedTask;
        }

        public bool ValidarAutenticacao(string? tokenRecebido) => true;
        public GatewayWebhookNotification? InterpretarWebhook(JsonElement payload) => null;
    }
}
